spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my-local-db
    username: my-local-db
    password: my-local-db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size:
            100
